brdName = '<board>'
userToken = '<thingsboard access token>'
adcScl = 540
mqttHost2 = None
mqttTopic2 = None
highPin = None
lowPin = None
oneWirePin = None
dhtPin = None
sht30Pins = None
minTime = 600
nomVolts = 4000
