brdName = 'proD1c'
userToken = 'QgiO3LkFHZXaimprIyj9'
adcScl = 1604
mqttHost2 = None
mqttTopic2 = None
highPin = None
lowPin = None
oneWirePin = 2
dhtPin = None
sht30Pins = (4, 5)
minTime = 30
nomVolts = 12500
