brdName = 'minD1a'
userToken = '7tUeObZDvJxSERHcMrro'
adcScl = 1571
mqttHost2 = ('thingsboard.balsk.ca',1886)
mqttTopic2 = 'station/relay'
highPin = None
lowPin = None
oneWirePin = 2
dhtPin = None
sht30Pins = (4, 5)
minTime = 30
nomVolts = 12500
