brdName = 'proD1d'
userToken = 'omB1qkUf3Nqz9CbHhZBU'
adcScl = 445
mqttHost2 = None
mqttTopic2 = None
highPin = None
lowPin = None
oneWirePin = None
dhtPin = None
sht30Pins = (4, 5)
minTime = 600
nomVolts = 4000
